pipeline {

   agent any

   tools {
        maven 'maven:3.6.1'
    }

   stages {
        dir("worker") {
            stage('Build') {
                steps {
                    echo "Building worker application.."
                    sh 'mvn compile'
                }
            }

            stage('Test') {
                steps {
                    echo "Building worker application.."
                    sh 'mvn clean test'
                }
            }

            stage('Package') {
                steps {
                    echo "Building worker application.."
                    sh 'mvn compile'
                }
            }
        }
    }
    
    post {
        always {
            echo "Hello World!!"
        }
    }
}
