pipeline {

   agent any

   tools {
        maven 'mvn:3.6.1'
    }

   stages {

            stage('Build') {
                steps {
                    echo "Building worker application.."
        	    dir("worker") {
                    	sh 'mvn compile'
                    }
            	}
	    }

            stage('Test') {
                steps {
                    echo "Building worker application.."
        	    dir("worker") {
                    	sh 'mvn clean test'
                    }
            	}  
   	    }	

            stage('Package') {
                steps {
                    echo "Building worker application.."
        	    dir("worker") {
                    	sh 'mvn compile'
                    }
            	}
	    }
    }
    
    post {
        always {
            echo "Hello World!!"
        }
    }
}
